spring:
  datasource:
    url: jdbc:mysql://localhost:6020/financial
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

entry:
  begin-date: "2020-03-30 00:00:00"
  end-date: "2023-03-09 23:59:59"
